After incorporating feedback from the Kaggle community, as well as scientific and educational partners, the Artificial Intelligence Committee of the American Meteorological Society is excited to be running a second iteration of the How Much Did It Rain? competition.

How Much Did It Rain? II is focused on solving the same core rain measurement prediction problem, but approaches it with a new and improved dataset and evaluation metric. This competition will go even further towards building a useful educational tool for universities, as well as making a meaningful contribution to continued meteorological research.

Competition Description
Rainfall is highly variable across space and time, making it notoriously tricky to measure. Rain gauges can be an effective measurement tool for a specific location, but it is impossible to have them everywhere. In order to have widespread coverage, data from weather radars is used to estimate rainfall nationwide. Unfortunately, these predictions never exactly match the measurements taken using rain gauges.

Recently, in an effort to improve their rainfall predictors, the U.S. National Weather Service upgraded their radar network to be polarimetric. These polarimetric radars are able to provide higher quality data than conventional Doppler radars because they transmit radio wave pulses with both horizontal and vertical orientations. 

Polarimetric radar. Image courtesy NOAA

Dual pulses make it easier to infer the size and type of precipitation because rain drops become flatter as they increase in size, whereas ice crystals tend to be elongated vertically.

In this competition, you are given snapshots of polarimetric radar values and asked to predict the hourly rain gauge total. A word of caution: many of the gauge values in the training dataset are implausible (gauges may get clogged, for example). More details are on the data page.

The training data consists of NEXRAD and MADIS data collected on 20 days between Apr and Aug 2014 over midwestern corn-growing states. Time and location information have been censored, and the data have been shuffled so that they are not ordered by time or place. The test data consists of data from the same radars and gauges over the remaining days in that month. Please see this page to understand more about polarimetric radar measurements.

File descriptions
train.zip - the training set.  This consists of radar observations at gauges in the Midwestern US over 20 days each month during the corn growing season. You are also provided the gauge observation at the end of each hour.
test.zip - the test set.  This consists of radar observations at gauges in the Midwestern US over the remaining 10/11 days each month of the same year(s) as the training set.  You are required to predict the gauge observation at the end of each hour.
sample_solution.zip - a sample submission file in the correct format
sample_dask.py - Example program in Python that will produce the sample submission file.  This program applies the Marshall-Palmer relationship to the radar observations to predict the gauge observation.
Data columns
To understand the data, you have to realize that there are multiple radar observations over the course of an hour, and only one gauge observation (the 'Expected'). That is why there are multiple rows with the same 'Id'.

The columns in the datasets are:

Id:  A unique number for the set of observations over an hour at a gauge.
minutes_past:  For each set of radar observations, the minutes past the top of the hour that the radar observations were carried out.  Radar observations are snapshots at that point in time.

radardist_km:  Distance of gauge from the radar whose observations are being reported.

Ref:  Radar reflectivity in km

Ref_5x5_10th:   10th percentile of reflectivity values in 5x5 neighborhood 
around the gauge.

Ref_5x5_50th:   50th percentile

Ref_5x5_90th:   90th percentile

RefComposite:  Maximum reflectivity in the vertical column above gauge.  In dBZ.

RefComposite_5x5_10th

RefComposite_5x5_50th

RefComposite_5x5_90th

RhoHV:  Correlation coefficient (unitless)

RhoHV_5x5_10th

RhoHV_5x5_50th

RhoHV_5x5_90th

Zdr:    Differential reflectivity in dB

Zdr_5x5_10th

Zdr_5x5_50th

Zdr_5x5_90th

Kdp:  Specific differential phase (deg/km)

Kdp_5x5_10th

Kdp_5x5_50th

Kdp_5x5_90th

Expected:  Actual gauge observation in mm at the end of the hour.


In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
!ls "/content/drive/My Drive/"

'Colab Notebooks'  'Data Files'   HMDIR   house_prices	 pics   UNIBS


Загрузка данных с Google Drive

In [ ]:
import numpy as np
import pandas as pd
data = pd.read_csv("/content/drive/My Drive/HMDIR/train.csv")

Отображение загруженных данных

In [ ]:
data = data.loc[:1000000]
data

Id  minutes_past  ...  Kdp_5x5_90th  Expected
0            1             3  ...           NaN  0.254000
1            1            16  ...           NaN  0.254000
2            1            25  ...           NaN  0.254000
3            1            35  ...           NaN  0.254000
4            1            45  ...           NaN  0.254000
...        ...           ...  ...           ...       ...
999996   87817            16  ...      8.139999  5.842003
999997   87817            21  ...      2.470001  5.842003
999998   87817            26  ...      3.529999  5.842003
999999   87817            31  ...      7.889999  5.842003
1000000  87817            35  ...      9.750000  5.842003

[1000001 rows x 24 columns]

In [ ]:
data_ids = data[~np.isnan(data.loc[:,'Ref'])].Id.unique()  
##good_ids = set(data.iloc[data[first:last].notna(), 'Id'])
data = data[np.in1d(data.Id, data_ids)]

In [ ]:
data

Id  minutes_past  ...  Kdp_5x5_90th  Expected
6            2             1  ...      1.059998  1.016000
7            2             6  ...      1.409988  1.016000
8            2            11  ...      1.759994  1.016000
9            2            16  ...      1.059998  1.016000
10           2            21  ...      1.759994  1.016000
...        ...           ...  ...           ...       ...
999996   87817            16  ...      8.139999  5.842003
999997   87817            21  ...      2.470001  5.842003
999998   87817            26  ...      3.529999  5.842003
999999   87817            31  ...      7.889999  5.842003
1000000  87817            35  ...      9.750000  5.842003

[645568 rows x 24 columns]

In [ ]:
data = data.fillna(0.0)

Удаление столбца ID из набора данных

In [ ]:
data = data.drop(columns=['Id'])

In [ ]:
features = data.drop(columns = ['Expected'])

In [ ]:
features

minutes_past  radardist_km  ...  Kdp_5x5_50th  Kdp_5x5_90th
6                   1           2.0  ...     -0.350006      1.059998
7                   6           2.0  ...      0.000000      1.409988
8                  11           2.0  ...     -0.350006      1.759994
9                  16           2.0  ...      0.000000      1.059998
10                 21           2.0  ...     -0.350006      1.759994
...               ...           ...  ...           ...           ...
999996             16           6.0  ...      0.000000      8.139999
999997             21           6.0  ...     -0.710007      2.470001
999998             26           6.0  ...      0.349991      3.529999
999999             31           6.0  ...     -2.120010      7.889999
1000000            35           6.0  ...      0.000000      9.750000

[645568 rows x 22 columns]

In [ ]:
#features.describe()

Нормировка данных так, чтобы среднее = 0, стандартное отклонение = 1

In [ ]:
# Среднее значение
mymean = features.mean(axis=0)
# Стандартное отклонение
mystd = features.std(axis=0)
features -= mymean
features /= mystd

In [ ]:
features

minutes_past  radardist_km  ...  Kdp_5x5_50th  Kdp_5x5_90th
6           -1.643490     -1.923638  ...     -0.097710     -0.315630
7           -1.355481     -1.923638  ...      0.133034     -0.216385
8           -1.067472     -1.923638  ...     -0.097710     -0.117136
9           -0.779464     -1.923638  ...      0.133034     -0.315630
10          -0.491455     -1.923638  ...     -0.097710     -0.117136
...               ...           ...  ...           ...           ...
999996      -0.779464     -0.933387  ...      0.133034      1.692006
999997      -0.491455     -0.933387  ...     -0.335042      0.084197
999998      -0.203446     -0.933387  ...      0.363768      0.384774
999999       0.084563     -0.933387  ...     -1.264596      1.621115
1000000      0.314970     -0.933387  ...      0.133034      2.148545

[645568 rows x 22 columns]

In [ ]:
features.describe()

minutes_past  radardist_km  ...  Kdp_5x5_50th  Kdp_5x5_90th
count  6.455680e+05  6.455680e+05  ...  6.455680e+05  6.455680e+05
mean   5.147359e-16 -5.636598e-14  ...  4.264567e-14 -5.573984e-13
std    1.000000e+00  1.000000e+00  ...  1.000000e+00  1.000000e+00
min   -1.701092e+00 -2.418763e+00  ... -3.759620e+01 -2.313122e+01
25%   -8.946671e-01 -6.858244e-01  ...  1.330340e-01 -6.162076e-01
50%    2.696130e-02  5.686362e-02  ...  1.330340e-01 -4.148793e-01
75%    8.333861e-01  7.995516e-01  ...  1.330340e-01  4.046215e-01
max    1.697413e+00  2.780053e+00  ...  7.193661e+00  2.305007e+01

[8 rows x 22 columns]

In [ ]:
y = data.iloc[:, 22]

In [ ]:
y

6          1.016000
7          1.016000
8          1.016000
9          1.016000
10         1.016000
             ...   
999996     5.842003
999997     5.842003
999998     5.842003
999999     5.842003
1000000    5.842003
Name: Expected, Length: 645568, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features, y, test_size=0.33, random_state=420)

In [ ]:
X_train

minutes_past  radardist_km  ...  Kdp_5x5_50th  Kdp_5x5_90th
676494     -0.030640      1.294677  ...      0.133034     -0.616208
975388      0.199767      0.551989  ...     -1.264596      0.977423
13248       1.236599      0.056864  ...     -0.097710      0.481185
533362     -1.182676     -1.180950  ...      0.133034     -0.616208
390044     -0.376251     -2.171200  ...     -1.726073      1.198603
...              ...           ...  ...           ...           ...
268241     -1.413083     -1.923638  ...      0.363768     -0.117136
805372      0.890988      0.056864  ...      0.133034      0.268512
913654     -0.030640      1.542240  ...      0.133034     -0.616208
996895      0.430174      1.047114  ...     -6.901228      0.484019
293968     -0.088242     -0.933387  ...      1.055989      1.025628

[432530 rows x 22 columns]

In [ ]:
y_test

229935     0.762000
347466    22.860012
173570     1.524001
581777     0.508000
864365     3.810002
            ...    
458043    28.000013
850053     7.112004
410357     0.010000
112005    15.240008
451419     0.254000
Name: Expected, Length: 213038, dtype: float64

In [ ]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(32, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(512, activation='relu'))
model.add(Dense(1))

In [ ]:
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [ ]:
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/10
10814/10814 [==============================] - 29s 3ms/step - loss: 44797.7344 - mae: 36.7012 - val_loss: 45563.0977 - val_mae: 36.4290
Epoch 2/10
10814/10814 [==============================] - 27s 3ms/step - loss: 44662.9570 - mae: 36.9826 - val_loss: 45504.3594 - val_mae: 33.3508
Epoch 3/10
10814/10814 [==============================] - 27s 2ms/step - loss: 44439.0352 - mae: 37.0790 - val_loss: 45303.3867 - val_mae: 35.9981
Epoch 4/10
10814/10814 [==============================] - 27s 3ms/step - loss: 44195.7383 - mae: 37.1597 - val_loss: 45257.7070 - val_mae: 32.1884
Epoch 5/10
10814/10814 [==============================] - 27s 3ms/step - loss: 43896.9102 - mae: 36.9809 - val_loss: 46124.9766 - val_mae: 36.8116
Epoch 6/10
10814/10814 [==============================] - 27s 2ms/step - loss: 43698.6211 - mae: 36.9840 - val_loss: 45099.2812 - val_mae: 32.1365
Epoch 7/10
10814/10814 [==============================] - 27s 3ms/step - loss: 43592.2852 - mae: 36.9503 - val_loss: 4

In [ ]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                736       
_________________________________________________________________
dense_1 (Dense)              (None, 128)               4224      
_________________________________________________________________
dense_2 (Dense)              (None, 512)               66048     
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 513       
Total params: 71,521
Trainable params: 71,521
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
pred = model.predict(X_test)

In [ ]:
y_test = y_test.reset_index(drop=True)

In [ ]:
print("Предсказанная стоимость:", pred[12][0], ", правильная стоимость:", y_test[12])

Предсказанная стоимость: 8.097883 , правильная стоимость: 36.322018


In [ ]:
vec = np.array([])
for i in np.arange(0, len(pred)):
  vec = np.append(vec, pred[i][0])
vec  

array([13.58607101,  7.37755585, 11.3064537 , ...,  5.2027607 ,
       14.14209557, 39.793396  ])

In [ ]:
diff = np.array([])

for i in np.arange(0, len(y_test)):
    diff = np.append(diff, np.abs(pred[i][0] - y_test[i]))

In [ ]:
np.sort(diff)[-10:-1]

array([ 4681.48413807,  4682.89441639,  4682.89441639,  4690.44164807,
        4690.68205983,  4701.01120907,  4702.21964032, 10375.86727321,
       10378.23661411])

In [ ]:
vec

array([13.58607101,  7.37755585, 11.3064537 , ...,  5.2027607 ,
       14.14209557, 39.793396  ])

In [ ]:
sorted = np.sort(pred, )
sorted

array([[13.586071 ],
       [ 7.377556 ],
       [11.306454 ],
       ...,
       [ 5.2027607],
       [14.142096 ],
       [39.793396 ]], dtype=float32)

In [ ]:
for i in np.arange(0, len(y_test)):
    print("Предсказанная стоимость:", pred[i][0], ", правильная стоимость:", y_test[i], 'разница: ', np.abs(pred[i][0] - y_test[i]))

Streaming output truncated to the last 5000 lines.
Предсказанная стоимость: 15.102652 , правильная стоимость: 545.84625 разница:  530.7435984039307
Предсказанная стоимость: 10.9805155 , правильная стоимость: 2.2860012000000003 разница:  8.694514280041503
Предсказанная стоимость: 8.124468 , правильная стоимость: 2.2860012000000003 разница:  5.838466649731445
Предсказанная стоимость: 6.59002 , правильная стоимость: 0.7620004 разница:  5.828019779748535
Предсказанная стоимость: 9.9456415 , правильная стоимость: 0.010000005 разница:  9.93564151263916
Предсказанная стоимость: 7.5654845 , правильная стоимость: 0.7620004 разница:  6.803484123773194
Предсказанная стоимость: 16.685946 , правильная стоимость: 5.334003 разница:  11.351942510864259
Предсказанная стоимость: 33.138184 , правильная стоимость: 0.54000026 разница:  32.59818333375
Предсказанная стоимость: 11.845154 , правильная стоимость: 0.7620004 разница:  11.08315340859375
Предсказанная стоимость: 8.879139 , правильная стоимость: 2.7

In [ ]:
СС_tuner = np.corrcoef(vec, y_test)
СС_tuner = СС_tuner[0][1]
print(f'Коэффициаент корреляция с истинными данными: {СС_tuner}')

Коэффициаент корреляция с истинными данными: 0.17616991482601785
