# Оценка стоимости недвижимости с помощью нейронной сети


Чтобы запускать и редактировать код, сохраните копию этого ноутбука себе (File->Save a copy in Drive...). Свою копию вы сможете изменять и запускать.

In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


Загрузка данных с Google Drive

In [2]:
import pandas as pd
data = pd.read_csv("/content/drive/My Drive/train.csv")

Отображение загруженных данных

In [3]:
data

Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0        1          60       RL  ...        WD         Normal    208500
1        2          20       RL  ...        WD         Normal    181500
2        3          60       RL  ...        WD         Normal    223500
3        4          70       RL  ...        WD        Abnorml    140000
4        5          60       RL  ...        WD         Normal    250000
...    ...         ...      ...  ...       ...            ...       ...
1455  1456          60       RL  ...        WD         Normal    175000
1456  1457          20       RL  ...        WD         Normal    210000
1457  1458          70       RL  ...        WD         Normal    266500
1458  1459          20       RL  ...        WD         Normal    142125
1459  1460          20       RL  ...        WD         Normal    147500

[1460 rows x 81 columns]

Удаление столбца ID из набора данных

In [4]:
features = data.drop(columns=['Id'])

In [5]:
features

MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
0             60       RL         65.0  ...        WD        Normal    208500
1             20       RL         80.0  ...        WD        Normal    181500
2             60       RL         68.0  ...        WD        Normal    223500
3             70       RL         60.0  ...        WD       Abnorml    140000
4             60       RL         84.0  ...        WD        Normal    250000
...          ...      ...          ...  ...       ...           ...       ...
1455          60       RL         62.0  ...        WD        Normal    175000
1456          20       RL         85.0  ...        WD        Normal    210000
1457          70       RL         66.0  ...        WD        Normal    266500
1458          20       RL         68.0  ...        WD        Normal    142125
1459          20       RL         75.0  ...        WD        Normal    147500

[1460 rows x 80 columns]

In [6]:
data_object = features.select_dtypes(include=[object])
data_object

MSZoning Street Alley LotShape  ...  Fence MiscFeature SaleType SaleCondition
0          RL   Pave   NaN      Reg  ...    NaN         NaN       WD        Normal
1          RL   Pave   NaN      Reg  ...    NaN         NaN       WD        Normal
2          RL   Pave   NaN      IR1  ...    NaN         NaN       WD        Normal
3          RL   Pave   NaN      IR1  ...    NaN         NaN       WD       Abnorml
4          RL   Pave   NaN      IR1  ...    NaN         NaN       WD        Normal
...       ...    ...   ...      ...  ...    ...         ...      ...           ...
1455       RL   Pave   NaN      Reg  ...    NaN         NaN       WD        Normal
1456       RL   Pave   NaN      Reg  ...  MnPrv         NaN       WD        Normal
1457       RL   Pave   NaN      Reg  ...  GdPrv        Shed       WD        Normal
1458       RL   Pave   NaN      Reg  ...    NaN         NaN       WD        Normal
1459       RL   Pave   NaN      Reg  ...    NaN         NaN       WD        Normal

[1460 rows x 43 columns]

In [7]:
import numpy as np
data_int = features.select_dtypes(include=[np.number])
data_int

MSSubClass  LotFrontage  LotArea  ...  MoSold  YrSold  SalePrice
0             60         65.0     8450  ...       2    2008     208500
1             20         80.0     9600  ...       5    2007     181500
2             60         68.0    11250  ...       9    2008     223500
3             70         60.0     9550  ...       2    2006     140000
4             60         84.0    14260  ...      12    2008     250000
...          ...          ...      ...  ...     ...     ...        ...
1455          60         62.0     7917  ...       8    2007     175000
1456          20         85.0    13175  ...       2    2010     210000
1457          70         66.0     9042  ...       5    2010     266500
1458          20         68.0     9717  ...       4    2010     142125
1459          20         75.0     9937  ...       6    2008     147500

[1460 rows x 37 columns]

In [8]:
data_object = data_object.dropna(axis = 'columns')
data_object

MSZoning Street LotShape  ... PavedDrive SaleType SaleCondition
0          RL   Pave      Reg  ...          Y       WD        Normal
1          RL   Pave      Reg  ...          Y       WD        Normal
2          RL   Pave      IR1  ...          Y       WD        Normal
3          RL   Pave      IR1  ...          Y       WD       Abnorml
4          RL   Pave      IR1  ...          Y       WD        Normal
...       ...    ...      ...  ...        ...      ...           ...
1455       RL   Pave      Reg  ...          Y       WD        Normal
1456       RL   Pave      Reg  ...          Y       WD        Normal
1457       RL   Pave      Reg  ...          Y       WD        Normal
1458       RL   Pave      Reg  ...          Y       WD        Normal
1459       RL   Pave      Reg  ...          Y       WD        Normal

[1460 rows x 27 columns]

In [9]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
subdata_encoded = data_object.apply(le.fit_transform)
subdata_encoded

MSZoning  Street  LotShape  ...  PavedDrive  SaleType  SaleCondition
0            3       1         3  ...           2         8              4
1            3       1         3  ...           2         8              4
2            3       1         0  ...           2         8              4
3            3       1         0  ...           2         8              0
4            3       1         0  ...           2         8              4
...        ...     ...       ...  ...         ...       ...            ...
1455         3       1         3  ...           2         8              4
1456         3       1         3  ...           2         8              4
1457         3       1         3  ...           2         8              4
1458         3       1         3  ...           2         8              4
1459         3       1         3  ...           2         8              4

[1460 rows x 27 columns]

In [10]:
subdata_encoded.reset_index(drop=True, inplace=True)
data_int.reset_index(drop=True, inplace=True)

In [11]:
data_2 = pd.concat([subdata_encoded, data_int], axis = 1)
data_2

MSZoning  Street  LotShape  ...  MoSold  YrSold  SalePrice
0            3       1         3  ...       2    2008     208500
1            3       1         3  ...       5    2007     181500
2            3       1         0  ...       9    2008     223500
3            3       1         0  ...       2    2006     140000
4            3       1         0  ...      12    2008     250000
...        ...     ...       ...  ...     ...     ...        ...
1455         3       1         3  ...       8    2007     175000
1456         3       1         3  ...       2    2010     210000
1457         3       1         3  ...       5    2010     266500
1458         3       1         3  ...       4    2010     142125
1459         3       1         3  ...       6    2008     147500

[1460 rows x 64 columns]

Нормировка данных так, чтобы среднее = 0, стандартное отклонение = 1

In [12]:
# Среднее значение
mymean = data_2.mean(axis=0)
# Стандартное отклонение
mystd = data_2.std(axis=0)
data_2 -= mymean
data_2 /= mystd

In [13]:
data_2 
data_2 = data_2.dropna(axis = 'columns')
data_2.describe()

MSZoning        Street  ...        YrSold     SalePrice
count  1.460000e+03  1.460000e+03  ...  1.460000e+03  1.460000e+03
mean  -4.601627e-16  6.849734e-16  ...  3.563078e-14  1.102999e-16
std    1.000000e+00  1.000000e+00  ...  1.000000e+00  1.000000e+00
min   -4.792221e+00 -1.556173e+01  ... -1.367186e+00 -1.838074e+00
25%   -4.551634e-02  6.421621e-02  ... -6.142282e-01 -6.412965e-01
50%   -4.551634e-02  6.421621e-02  ...  1.387300e-01 -2.255870e-01
75%   -4.551634e-02  6.421621e-02  ...  8.916881e-01  4.163867e-01
max    1.536718e+00  6.421621e-02  ...  1.644646e+00  7.226343e+00

[8 rows x 61 columns]

In [14]:
y = data.iloc[:, 80]

In [15]:
y

0       208500
1       181500
2       223500
3       140000
4       250000
         ...  
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [16]:
import numpy as np
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(data_2, y, test_size=0.33, random_state=42)

In [18]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense

In [19]:
model = Sequential()
model.add(Dense(32, activation='relu', input_shape=(data_2.shape[1],)))
model.add(Dense(128, activation='relu'))
model.add(Dense(512, activation='relu'))
model.add(Dense(1))

In [21]:
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [22]:
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/10
25/25 [==============================] - 1s 14ms/step - loss: 38659596288.0000 - mae: 180876.7656 - val_loss: 38210060288.0000 - val_mae: 181657.5469
Epoch 2/10
25/25 [==============================] - 0s 3ms/step - loss: 38620688384.0000 - mae: 180782.4375 - val_loss: 38113665024.0000 - val_mae: 181431.1875
Epoch 3/10
25/25 [==============================] - 0s 3ms/step - loss: 38391898112.0000 - mae: 180251.8125 - val_loss: 37632323584.0000 - val_mae: 180363.2031
Epoch 4/10
25/25 [==============================] - 0s 3ms/step - loss: 37456551936.0000 - mae: 178183.5156 - val_loss: 36011921408.0000 - val_mae: 176846.6875
Epoch 5/10
25/25 [==============================] - 0s 3ms/step - loss: 34905538560.0000 - mae: 172431.5312 - val_loss: 32004980736.0000 - val_mae: 167908.9844
Epoch 6/10
25/25 [==============================] - 0s 4ms/step - loss: 29326555136.0000 - mae: 159338.1875 - val_loss: 24665184256.0000 - val_mae: 149605.6562
Epoch 7/10
25/25 [=====================

In [23]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                1984      
_________________________________________________________________
dense_1 (Dense)              (None, 128)               4224      
_________________________________________________________________
dense_2 (Dense)              (None, 512)               66048     
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 513       
Total params: 72,769
Trainable params: 72,769
Non-trainable params: 0
_________________________________________________________________
None


In [24]:
pred = model.predict(X_test)

In [25]:
y_test = y_test.reset_index(drop=True)

In [26]:
print("Предсказанная стоимость:", pred[12][0], ", правильная стоимость:", y_test[12])

Предсказанная стоимость: 17186.275 , правильная стоимость: 81000


In [27]:
vec = np.array([])
for i in np.arange(0, len(pred)):
  vec = np.append(vec, pred[i][0])
vec  

array([ 94832.6875    , 334551.5       ,  83692.015625  ,  77365.640625  ,
       356607.84375   , 119786.9140625 , 111256.9140625 ,  40436.38671875,
       129751.4375    ,  82820.3515625 ,  82728.296875  ,  92904.921875  ,
        17186.27539062, 149663.171875  ,  93299.5390625 ,  66304.2265625 ,
       173426.328125  ,  64401.37109375, 114716.515625  , 185202.96875   ,
        67198.96875   , 182578.4375    , 118847.84375   ,  84579.171875  ,
       162853.703125  ,  56344.3515625 , 151661.25      ,  71569.7421875 ,
       131528.921875  , 202314.828125  ,  76515.0625    , 304793.71875   ,
        82132.265625  ,  80749.671875  , 309293.59375   ,  70555.90625   ,
        58830.9375    , 185007.921875  , 318210.84375   ,  94973.234375  ,
        69024.015625  , 250514.828125  ,  85274.3125    , 459500.34375   ,
        65967.6640625 ,  61016.08984375,  98167.796875  ,  80885.984375  ,
       543422.8125    ,  78362.578125  , 101360.875     , 137223.390625  ,
        73876.4921875 , 2

In [28]:
diff = np.array([])

for i in np.arange(0, len(y_test)):
    diff = np.append(diff, np.abs(pred[i][0] - y_test[i]))

In [29]:
np.sort(diff)[-10:-1]

array([149546.984375  , 152171.30078125, 157012.58398438, 166112.078125  ,
       172127.0390625 , 173882.3671875 , 178675.234375  , 188906.0625    ,
       200243.0859375 ])

In [30]:
vec

array([ 94832.6875    , 334551.5       ,  83692.015625  ,  77365.640625  ,
       356607.84375   , 119786.9140625 , 111256.9140625 ,  40436.38671875,
       129751.4375    ,  82820.3515625 ,  82728.296875  ,  92904.921875  ,
        17186.27539062, 149663.171875  ,  93299.5390625 ,  66304.2265625 ,
       173426.328125  ,  64401.37109375, 114716.515625  , 185202.96875   ,
        67198.96875   , 182578.4375    , 118847.84375   ,  84579.171875  ,
       162853.703125  ,  56344.3515625 , 151661.25      ,  71569.7421875 ,
       131528.921875  , 202314.828125  ,  76515.0625    , 304793.71875   ,
        82132.265625  ,  80749.671875  , 309293.59375   ,  70555.90625   ,
        58830.9375    , 185007.921875  , 318210.84375   ,  94973.234375  ,
        69024.015625  , 250514.828125  ,  85274.3125    , 459500.34375   ,
        65967.6640625 ,  61016.08984375,  98167.796875  ,  80885.984375  ,
       543422.8125    ,  78362.578125  , 101360.875     , 137223.390625  ,
        73876.4921875 , 2

In [31]:
sorted = np.sort(pred, )
sorted

array([[ 94832.69 ],
       [334551.5  ],
       [ 83692.016],
       [ 77365.64 ],
       [356607.84 ],
       [119786.914],
       [111256.914],
       [ 40436.387],
       [129751.44 ],
       [ 82820.35 ],
       [ 82728.3  ],
       [ 92904.92 ],
       [ 17186.275],
       [149663.17 ],
       [ 93299.54 ],
       [ 66304.23 ],
       [173426.33 ],
       [ 64401.37 ],
       [114716.516],
       [185202.97 ],
       [ 67198.97 ],
       [182578.44 ],
       [118847.84 ],
       [ 84579.17 ],
       [162853.7  ],
       [ 56344.35 ],
       [151661.25 ],
       [ 71569.74 ],
       [131528.92 ],
       [202314.83 ],
       [ 76515.06 ],
       [304793.72 ],
       [ 82132.266],
       [ 80749.67 ],
       [309293.6  ],
       [ 70555.91 ],
       [ 58830.938],
       [185007.92 ],
       [318210.84 ],
       [ 94973.234],
       [ 69024.016],
       [250514.83 ],
       [ 85274.31 ],
       [459500.34 ],
       [ 65967.664],
       [ 61016.09 ],
       [ 98167.8  ],
       [ 8088

In [32]:
for i in np.arange(0, len(y_test)):
    print("Предсказанная стоимость:", pred[i][0], ", правильная стоимость:", y_test[i], 'разница: ', np.abs(pred[i][0] - y_test[i]))

Предсказанная стоимость: 94832.69 , правильная стоимость: 154500 разница:  59667.3125
Предсказанная стоимость: 334551.5 , правильная стоимость: 325000 разница:  9551.5
Предсказанная стоимость: 83692.016 , правильная стоимость: 115000 разница:  31307.984375
Предсказанная стоимость: 77365.64 , правильная стоимость: 159000 разница:  81634.359375
Предсказанная стоимость: 356607.84 , правильная стоимость: 315500 разница:  41107.84375
Предсказанная стоимость: 119786.914 , правильная стоимость: 75500 разница:  44286.9140625
Предсказанная стоимость: 111256.914 , правильная стоимость: 311500 разница:  200243.0859375
Предсказанная стоимость: 40436.387 , правильная стоимость: 146000 разница:  105563.61328125
Предсказанная стоимость: 129751.44 , правильная стоимость: 84500 разница:  45251.4375
Предсказанная стоимость: 82820.35 , правильная стоимость: 135500 разница:  52679.6484375
Предсказанная стоимость: 82728.3 , правильная стоимость: 145000 разница:  62271.703125
Предсказанная стоимость: 92904.

In [33]:
СС_tuner = np.corrcoef(vec, y_test)
СС_tuner = СС_tuner[0][1]
print(f'Коэффициаент корреляция с истинными данными: {СС_tuner}')

Коэффициаент корреляция с истинными данными: 0.8669875228937916
