# Оценка стоимости недвижимости с помощью нейронной сети


Чтобы запускать и редактировать код, сохраните копию этого ноутбука себе (File->Save a copy in Drive...). Свою копию вы сможете изменять и запускать.

**Laboratory work n1 **
**Lisin Maxim 19АСв **
**Variant 6** 

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
!ls "/content/drive/My Drive/"

'2021-02-14 Оплата тёса'
 2021-03-29
'Cisco packet tracer'
'Colab Notebooks'
'English books'
 GitHub
'gora (1920x1080).jpg'
 IntelligentAnalysis
 Java_literature
 Netcracker
 risunok-minimalizm-raketa-doma-nebo-zapusk-ogon-dym.jpg
 wallhaven-xlx87d.png
'We build our house'
'Документы Россети'
 ИРИТ
'Квитанция об оплате ИРИТ'
'Ключи windows'
 Ленты
'На печать'


Загрузка данных с Google Drive

In [ ]:
import pandas as pd
data = pd.read_csv("/content/drive/My Drive/IntelligentAnalysis/BostonHousing.csv")

Отображение загруженных данных

In [ ]:
data

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0    0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1    0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2    0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3    0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4    0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2
..       ...   ...    ...   ...    ...  ...  ...      ...     ...    ...   ...
501  0.06263   0.0  11.93     0  0.573  ...  273     21.0  391.99   9.67  22.4
502  0.04527   0.0  11.93     0  0.573  ...  273     21.0  396.90   9.08  20.6
503  0.06076   0.0  11.93     0  0.573  ...  273     21.0  396.90   5.64  23.9
504  0.10959   0.0  11.93     0  0.573  ...  273     21.0  393.45   6.48  22.0
505  0.04741   0.0  11.93     0  0.573  ...  273     21.0  396.90   7.88  11.9

[506 rows x 14 columns]

Удаление столбца ID из набора данных

In [ ]:
features = data.drop(columns=['medv'])

In [ ]:
features

crim    zn  indus  chas    nox  ...  rad  tax  ptratio       b  lstat
0    0.00632  18.0   2.31     0  0.538  ...    1  296     15.3  396.90   4.98
1    0.02731   0.0   7.07     0  0.469  ...    2  242     17.8  396.90   9.14
2    0.02729   0.0   7.07     0  0.469  ...    2  242     17.8  392.83   4.03
3    0.03237   0.0   2.18     0  0.458  ...    3  222     18.7  394.63   2.94
4    0.06905   0.0   2.18     0  0.458  ...    3  222     18.7  396.90   5.33
..       ...   ...    ...   ...    ...  ...  ...  ...      ...     ...    ...
501  0.06263   0.0  11.93     0  0.573  ...    1  273     21.0  391.99   9.67
502  0.04527   0.0  11.93     0  0.573  ...    1  273     21.0  396.90   9.08
503  0.06076   0.0  11.93     0  0.573  ...    1  273     21.0  396.90   5.64
504  0.10959   0.0  11.93     0  0.573  ...    1  273     21.0  393.45   6.48
505  0.04741   0.0  11.93     0  0.573  ...    1  273     21.0  396.90   7.88

[506 rows x 13 columns]

Нормировка данных так, чтобы среднее = 0, стандартное отклонение = 1

In [ ]:
# Среднее значение
mymean = features.mean(axis=0)
# Стандартное отклонение
mystd = features.std(axis=0)
features -= mymean
features /= mystd

In [ ]:
features

crim        zn     indus  ...   ptratio         b     lstat
0   -0.419367  0.284548 -1.286636  ... -1.457558  0.440616 -1.074499
1   -0.416927 -0.487240 -0.592794  ... -0.302794  0.440616 -0.491953
2   -0.416929 -0.487240 -0.592794  ... -0.302794  0.396035 -1.207532
3   -0.416338 -0.487240 -1.305586  ...  0.112920  0.415751 -1.360171
4   -0.412074 -0.487240 -1.305586  ...  0.112920  0.440616 -1.025487
..        ...       ...       ...  ...       ...       ...       ...
501 -0.412820 -0.487240  0.115624  ...  1.175303  0.386834 -0.417734
502 -0.414839 -0.487240  0.115624  ...  1.175303  0.440616 -0.500355
503 -0.413038 -0.487240  0.115624  ...  1.175303  0.440616 -0.982076
504 -0.407361 -0.487240  0.115624  ...  1.175303  0.402826 -0.864446
505 -0.414590 -0.487240  0.115624  ...  1.175303  0.440616 -0.668397

[506 rows x 13 columns]

In [ ]:
y = data.iloc[:, 13]

In [ ]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features, y, test_size=0.33, random_state=42)

In [ ]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(128, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(64, activation='relu'))
model.add(Dense(1))

In [ ]:
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 128)               1792      
_________________________________________________________________
dense_10 (Dense)             (None, 64)                8256      
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 65        
Total params: 10,113
Trainable params: 10,113
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [ ]:
model.fit(X_train, y_train, epochs=15, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/15
9/9 [==============================] - 1s 24ms/step - loss: 615.9486 - mae: 22.9281 - val_loss: 562.5704 - val_mae: 22.1659
Epoch 2/15
9/9 [==============================] - 0s 5ms/step - loss: 566.3326 - mae: 21.8281 - val_loss: 515.0073 - val_mae: 21.1010
Epoch 3/15
9/9 [==============================] - 0s 5ms/step - loss: 512.5765 - mae: 20.5710 - val_loss: 455.3910 - val_mae: 19.6922
Epoch 4/15
9/9 [==============================] - 0s 5ms/step - loss: 439.8020 - mae: 18.8312 - val_loss: 376.9443 - val_mae: 17.6795
Epoch 5/15
9/9 [==============================] - 0s 7ms/step - loss: 347.8009 - mae: 16.4134 - val_loss: 282.3686 - val_mae: 15.0657
Epoch 6/15
9/9 [==============================] - 0s 5ms/step - loss: 245.5970 - mae: 13.3284 - val_loss: 184.3951 - val_mae: 11.6734
Epoch 7/15
9/9 [==============================] - 0s 5ms/step - loss: 154.7732 - mae: 10.0492 - val_loss: 107.7750 - val_mae: 8.1835
Epoch 8/15
9/9 [==============================] - 0s 5ms/step 

In [ ]:
pred = model.predict(X_test)

In [ ]:
#print(pred)
pred[0][0]

27.913511

In [ ]:
y_test = y_test.reset_index(drop=True)

In [ ]:
print("Предсказанная стоимость:", pred[12][0], ", правильная стоимость:", y_test[12])

Предсказанная стоимость: 9.555574 , правильная стоимость: 7.0


In [ ]:
vec = np.array([])
for i in np.arange(0, len(pred)):
  vec = np.append(vec, pred[i][0])

In [ ]:
diff = np.array([])

for i in np.arange(0, len(y_test)):
    diff = np.append(diff, np.abs(pred[i][0] - y_test[i]))

In [ ]:
np.sort(diff)[-10:-1]

array([ 7.92198944,  8.04927521,  8.20180817,  9.71830006, 10.01176453,
       10.21260262, 11.05205803, 11.29321098, 13.75947094])

In [ ]:
vec

array([27.91351128, 33.07550812, 21.3854866 , 25.4525547 , 16.67088699,
       16.38160515, 13.3341608 , 15.79588413, 17.44361687, 13.61918545,
       24.72789001, 16.9605999 ,  9.55557442, 15.97763824, 16.39876556,
       18.74794197, 19.6754303 , 13.03794956, 43.37545013, 16.04040146,
       26.016222  , 24.72901344, 11.06046391, 22.37815666, 15.97453499,
       14.32948017, 17.62802315, 11.41068172, 22.62134552, 11.9670248 ,
       20.10204887, 23.49717712, 20.4578228 , 19.53672218, 13.87842751,
       18.81546211, 35.05436707, 21.03286171, 23.1926136 , 24.57196999,
        9.98169994, 27.11530495, 44.29902267, 17.55528069, 27.81745338,
       16.82097244, 11.69877338, 26.42877388, 15.59602833, 31.92198944,
       19.15568161, 37.01682281, 13.99448681, 22.71923637, 42.85811996,
       15.02379513, 18.20618248, 28.73519897, 27.05946922, 13.18130302,
       22.79491806, 33.96515656, 28.61517143, 11.99819183, 25.43289375,
       19.16032982, 17.94096565, 23.98737907, 28.01028061, 11.35

In [ ]:
sorted = np.sort(pred, )
sorted

array([[27.913511 ],
       [33.07551  ],
       [21.385487 ],
       [25.452555 ],
       [16.670887 ],
       [16.381605 ],
       [13.334161 ],
       [15.795884 ],
       [17.443617 ],
       [13.619185 ],
       [24.72789  ],
       [16.9606   ],
       [ 9.555574 ],
       [15.977638 ],
       [16.398766 ],
       [18.747942 ],
       [19.67543  ],
       [13.03795  ],
       [43.37545  ],
       [16.040401 ],
       [26.016222 ],
       [24.729013 ],
       [11.060464 ],
       [22.378157 ],
       [15.974535 ],
       [14.32948  ],
       [17.628023 ],
       [11.410682 ],
       [22.621346 ],
       [11.967025 ],
       [20.102049 ],
       [23.497177 ],
       [20.457823 ],
       [19.536722 ],
       [13.8784275],
       [18.815462 ],
       [35.054367 ],
       [21.032862 ],
       [23.192614 ],
       [24.57197  ],
       [ 9.9817   ],
       [27.115305 ],
       [44.299023 ],
       [17.55528  ],
       [27.817453 ],
       [16.820972 ],
       [11.698773 ],
       [26.42

In [ ]:
for i in np.arange(0, len(y_test)):
    print("Предсказанная стоимость:", pred[i][0], ", правильная стоимость:", y_test[i], 'разница: ', np.abs(pred[i][0] - y_test[i]))

Предсказанная стоимость: 27.913511 , правильная стоимость: 23.6 разница:  4.313511276245116
Предсказанная стоимость: 33.07551 , правильная стоимость: 32.4 разница:  0.6755081176757827
Предсказанная стоимость: 21.385487 , правильная стоимость: 13.6 разница:  7.7854866027832035
Предсказанная стоимость: 25.452555 , правильная стоимость: 22.8 разница:  2.6525547027587884
Предсказанная стоимость: 16.670887 , правильная стоимость: 16.1 разница:  0.5708869934082017
Предсказанная стоимость: 16.381605 , правильная стоимость: 20.0 разница:  3.6183948516845703
Предсказанная стоимость: 13.334161 , правильная стоимость: 17.8 разница:  4.4658391952514656
Предсказанная стоимость: 15.795884 , правильная стоимость: 14.0 разница:  1.795884132385254
Предсказанная стоимость: 17.443617 , правильная стоимость: 19.6 разница:  2.1563831329345717
Предсказанная стоимость: 13.619185 , правильная стоимость: 16.8 разница:  3.1808145523071296
Предсказанная стоимость: 24.72789 , правильная стоимость: 21.5 разница:  